apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-lab-prod
resources:
  - ../../base
images:
  - name: ghcr.io/vkongkin/spring-k8s-lab
    newTag: <real-sha>
patches:
  - path: patch-replicas.yaml