spring.application.name=spring-k8s-lab
management.endpoints.web.exposure.include=health,info,refresh,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

app.greeting=${APP_GREETING:Hello from localhost}
app.db-password=${DB_PASSWORD:none}