---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spring-k8s-lab-secret
  namespace: spring-lab-helm
spec:
  encryptedData:
    DB_PASSWORD: AgAo8AEds2Ykr8Ts/xzJINZC5+lM8B0Hv/MojqMenYmKQ4+oA+x6Xy/gKLpjArWpINwwXuMkXAUWkUorE6f0nsnED0xVD/ITNTwQ/sOM25SZp7bdqkyDP67SEyUiMma5AWrdpJJPFT4cl0s78FcV06xs/kS+tJaDqQJHmt8+Wb/Pm0A6p6LpAshTqgE8q4ORpTytythTgAmmHXyn5RtX8aOB7a5yv3Yd3xB51XsWfC9HifQiFw4cI4S/ez3VxMkzxS2rEEtp9k+XMuFsHG2Z2fcj3QwwMrtB9Re0fwENvEIs1/Udvb5UnKtQKWmfgez5k32tn3ILaFZLIRg+xv6lBeVQwjfUIViAGBmQoPhcu62mN0XIHNw9SHw/k1dPjLEL0Cm4dWepbLJtfMP/kgovfYFTYxXn6PPR5XMljYGasmsboDwskTemSt78rvdHXEEjDg04y3Hn2hHFcVCXyVU69H1uwi7efLGY3cZAGj/TUkOKQdtp2Xdgj88CqjAW65WDG9JAlk6vjRHmz8h/7tmnwRyhodZKbidpWF9lqim4udzfTOMlYzQGiOE7rt3hQCD2GRpYOMjIrgkhfh/qB06wguvXBt2XJkN2V1pcturyMdVCSc7HhOaPd0SmSO+pAaVARlFKrBCwMqXN/nAJQ37/HjkSrsnHmVOqAFrGJ7BzMPRvvUz+vwiHQJyOZHrQTaMECsiZIvoGVSwb1j/5xXZs9eY=
  template:
    metadata:
      name: spring-k8s-lab-secret
      namespace: spring-lab-helm
