apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-lab
  namespace: argocd
spec:
  description: Spring Boot lab
  sourceRepos:
    - https://github.com/VKongkin/spring-k8s-lab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: spring-lab
    - server: https://kubernetes.default.svc
      namespace: spring-lab-helm
  clusterResourceWhitelist: []