---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spring-k8s-lab-secret
  namespace: spring-lab
spec:
  encryptedData:
    DB_PASSWORD: AgAmryMJjB+jH73sI7/sIJV94AswQeD8a+uE0mj6kJnXiDV4aQJ5FCp5s9ZVCHFvQdtemlyP0jSrF///kHaVlGtBVSPmquXihng5zSwLtppOlBf5Wjmx+6Q3B97aUUwG9FvznDEYYLjfh7w/J77NMUWTOsqJ84D81rUmu77wFJjKpfpwKyoQNtnNJkkfPgAVXVLnjyt4+YQ6ApLuDomrDtc14JLTcGKjv5FRyqXTfcH+kRNEEqnm15xOYYxRwKx/ZK2tCvi6RKUqU23G3naE0ETPu0tceQ2jVNInn9n7FHyAImMtCHw28kJscJL5eokdFNzO9KZlSsk/Y8rAoDQp9+zjFeeaJDyR6qophBh5+juvu55TaogBrj6Qi93TP55mbY38OwXW8NE2I6FlZYgFqTOBePpk3JgVodfVGta/dZ5hDQ5u95Fjm0Xa/iQ1wEC65rl515QdK+GOcW6zQKWCRPuCXGzgzPyF2HQCUfc2xCwqQAmg6alLJ0ncDH6uuPs9VH4WILrF3iENEZj9iDVfwrtyuJkW3EfrpFwP5dtNnnPgLjgSPj0YC1AC+sNAcFXY5ff10UO2pj/wtWoKIzWXW3l25quIudnulUaylK0lUCLBLUA/NlyS5IfyoSIalTl0ACQieeselZy6/VIBlzkjfv5NKkFwTiOeVTYa01cc5U5w1oMFr/lpbxK2p4ki60zSiJYZQAZ4XbR9KerrNgl1nR0=
  template:
    metadata:
      name: spring-k8s-lab-secret
      namespace: spring-lab
