apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-lab
resources:
  - ../../base
images:
  - name: ghcr.io/vkongkin/spring-k8s-lab
    newTag: d2fc4b0
patches:
  - path: patch-replicas.yaml